experimenter: MC
prep_choices: [Left optic lobe, Right optic lobe, Whole brain, Optic glomeruli]
driver_choices: [Tm3 (R13E12-Gal4), Tm3 (R13E12-LexA), nSyb-Gal4]
indicator_choices: [TdTomato, GCaMP7f, GCaMP6f, GCaMP6m, Syt1GCaMP6f, SytGCaMP6S, Syt1GCaMP7FU, GCaMP6S.brpS.mCherry, ASAP2f, ASAP4c, ASAP4c_F413G, 10_90_GCaMP6f, 10_90_GCaMP7f, 10_90_ASAP2f, 10_90_ASAP4c, 10_90_ASAP4c_F413G, SF-iGluSnFR.A184V]

rig_config:
  Bruker_LeftScreen:
    data_directory: E:/Minseung/FlystimData
    screen_center: [0,-30]
    rig: Bruker

  Bruker_TwoScreens:
    data_directory: E:/Minseung/FlystimData
    screen_center: [0, 0]
    rig: Bruker

  Laptop:
    data_directory: /Volumes/GoogleDrive/My\ Drive/research/clandinin_lab/data/FlystimData
    screen_center: [0, 0]
    rig: (testing)
