experimenter: MHT
prep_choices: [Left optic lobe, Right optic lobe, Whole brain, Optic glomeruli]
driver_choices: [L2,LC4, LC6, LC9, LC11, LC12, LC15, LC16, LC17, LC18, LC20, LC21, LC22, LC26, nSyb-Gal4]
indicator_choices: [TdTomato, GCaMP7f, GCaMP6f, GCaMP6m,ASAP2f, ASAP4c, ASAP4c_F413G, 10_90_GCaMP6f, 10_90_GCaMP7f, 10_90_ASAP2f, 10_90_ASAP4c, 10_90_ASAP4c_F413G, SF-iGluSnFR.A184V]

rig_config:
  AODscope_OneScreen:
    data_directory: D:/Max/FlystimData
    screen_center: [0, 180]
    rig: AODscope

  Bruker_LeftScreen:
    data_directory: E:/Max/FlystimData
    screen_center: [225,-30]
    rig: Bruker

  Laptop:
    data_directory: C:/Users/mhturner/Dropbox/ClandininLab/CurrentData/FlystimData
    screen_center: [0, 0]
    rig: (testing)